<?php

use Illuminate\Database\Seeder;

class SystemTdsdetailsMastTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('system_tdsdetails_mast')->delete();
        
        \DB::table('system_tdsdetails_mast')->insert(array (
            0 => 
            array (
                'id' => 1,
                'slab' => 1,
                'fy' => 2,
                'amount' => 300000.0,
                'percent' => 1.0,
                'status' => 1,
                'created_at' => '2018-01-05 18:05:34',
                'updated_at' => '2018-01-12 06:07:19',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 2,
                'updated_by' => 2,
            ),
            1 => 
            array (
                'id' => 2,
                'slab' => 1,
                'fy' => 2,
                'amount' => 400000.0,
                'percent' => 1.0,
                'status' => 1,
                'created_at' => '2018-01-05 18:06:22',
                'updated_at' => '2018-01-12 06:14:19',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 2,
                'updated_by' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'slab' => 2,
                'fy' => 2,
                'amount' => 100000.0,
                'percent' => 15.0,
                'status' => 1,
                'created_at' => '2018-01-05 18:07:07',
                'updated_at' => '2018-01-12 06:10:54',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 2,
                'updated_by' => 2,
            ),
            3 => 
            array (
                'id' => 4,
                'slab' => 2,
                'fy' => 2,
                'amount' => 100000.0,
                'percent' => 15.0,
                'status' => 1,
                'created_at' => '2018-01-05 18:07:47',
                'updated_at' => '2018-01-12 06:14:41',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 2,
                'updated_by' => 2,
            ),
            4 => 
            array (
                'id' => 5,
                'slab' => 3,
                'fy' => 2,
                'amount' => 450000.0,
                'percent' => 25.0,
                'status' => 1,
                'created_at' => '2018-01-05 18:08:50',
                'updated_at' => '2018-01-12 06:11:28',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 2,
                'updated_by' => 2,
            ),
            5 => 
            array (
                'id' => 6,
                'slab' => 3,
                'fy' => 2,
                'amount' => 500000.0,
                'percent' => 25.0,
                'status' => 1,
                'created_at' => '2018-01-05 18:09:25',
                'updated_at' => '2018-01-12 06:15:53',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 2,
                'updated_by' => 2,
            ),
            6 => 
            array (
                'id' => 7,
                'slab' => 4,
                'fy' => 2,
                'amount' => 2500000.0,
                'percent' => 35.0,
                'status' => 1,
                'created_at' => '2018-01-08 17:00:59',
                'updated_at' => '2018-01-12 06:16:31',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 2,
            ),
            7 => 
            array (
                'id' => 8,
                'slab' => 4,
                'fy' => 2,
                'amount' => 2500000.0,
                'percent' => 35.0,
                'status' => 1,
                'created_at' => '2018-01-12 06:13:55',
                'updated_at' => '2018-01-12 06:13:55',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 2,
                'updated_by' => 2,
            ),
            8 => 
            array (
                'id' => 9,
                'slab' => 1,
                'fy' => 3,
                'amount' => 350000.0,
                'percent' => 1.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:00:02',
                'updated_at' => '2019-08-07 10:00:02',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'slab' => 2,
                'fy' => 3,
                'amount' => 100000.0,
                'percent' => 10.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:00:15',
                'updated_at' => '2019-08-07 10:09:32',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'slab' => 3,
                'fy' => 3,
                'amount' => 200000.0,
                'percent' => 20.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:00:36',
                'updated_at' => '2019-08-07 10:18:10',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'slab' => 4,
                'fy' => 3,
                'amount' => 1350000.0,
                'percent' => 30.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:01:04',
                'updated_at' => '2019-08-07 10:18:14',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'slab' => 5,
                'fy' => 3,
                'amount' => 10000000.0,
                'percent' => 36.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:02:22',
                'updated_at' => '2019-08-07 10:02:22',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'slab' => 1,
                'fy' => 3,
                'amount' => 400000.0,
                'percent' => 1.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:05:23',
                'updated_at' => '2019-08-07 10:05:23',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'slab' => 2,
                'fy' => 3,
                'amount' => 100000.0,
                'percent' => 10.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:05:45',
                'updated_at' => '2019-08-07 10:16:49',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'slab' => 3,
                'fy' => 3,
                'amount' => 200000.0,
                'percent' => 20.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:06:00',
                'updated_at' => '2019-08-07 10:16:56',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'slab' => 4,
                'fy' => 3,
                'amount' => 1300000.0,
                'percent' => 30.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:07:49',
                'updated_at' => '2019-08-07 10:17:12',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'slab' => 5,
                'fy' => 3,
                'amount' => 10000000.0,
                'percent' => 36.0,
                'status' => 1,
                'created_at' => '2019-08-07 10:08:12',
                'updated_at' => '2019-08-07 10:08:12',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'slab' => 1,
                'fy' => 4,
                'amount' => 400000.0,
                'percent' => 1.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:40:21',
                'updated_at' => '2019-08-07 11:40:21',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'slab' => 2,
                'fy' => 4,
                'amount' => 100000.0,
                'percent' => 10.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:40:32',
                'updated_at' => '2019-08-07 11:40:32',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'slab' => 3,
                'fy' => 4,
                'amount' => 200000.0,
                'percent' => 20.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:40:43',
                'updated_at' => '2019-08-07 11:40:43',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'slab' => 4,
                'fy' => 4,
                'amount' => 1300000.0,
                'percent' => 30.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:41:27',
                'updated_at' => '2019-08-07 11:41:27',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'slab' => 5,
                'fy' => 4,
                'amount' => 2000000.0,
                'percent' => 36.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:41:43',
                'updated_at' => '2019-08-07 11:42:06',
                'deleted_at' => NULL,
                'type' => 0,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'slab' => 1,
                'fy' => 4,
                'amount' => 450000.0,
                'percent' => 1.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:42:38',
                'updated_at' => '2019-08-07 11:42:38',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'slab' => 2,
                'fy' => 4,
                'amount' => 100000.0,
                'percent' => 10.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:42:50',
                'updated_at' => '2019-08-07 11:42:50',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'slab' => 3,
                'fy' => 4,
                'amount' => 200000.0,
                'percent' => 20.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:43:04',
                'updated_at' => '2019-08-07 11:43:04',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'slab' => 4,
                'fy' => 4,
                'amount' => 1250000.0,
                'percent' => 30.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:43:27',
                'updated_at' => '2019-08-07 11:43:27',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'slab' => 5,
                'fy' => 4,
                'amount' => 2000000.0,
                'percent' => 36.0,
                'status' => 1,
                'created_at' => '2019-08-07 11:43:44',
                'updated_at' => '2019-08-07 11:43:44',
                'deleted_at' => NULL,
                'type' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ),
        ));
        
        
    }
}