<?php

namespace Tests;

use App\User;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->be(User::first());
        $this->withSession(['role' => true]);
    }
}
